### ISSUE TITLE
Error: API rate limit exceeded for 73.158.63.232. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

### ISSUE THREAD

**Issue by litinskii** [doowb/update-contributors#2]
Get error Error: API rate limit exceeded for 73.158.63.232. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by doowb** [comment]
@w-site are you using the cli or the api? Github requires authentication if you do a lot of requests. This library is supposed to prompt you for credentials if you don't provide them.

If you're using the cli, a screenshot of the output would be helpful (please make sure to remove any passwords or github tokens)

**Comment by litinskii** [comment]
@doowb  I'm using cli, but now if i'm try to do update-contrib all work fine, probably problem was in limit of request, in any way thanks for answer.
